# Generated by Django 2.1.7 on 2019-04-24 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_move_follower_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='follow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
