# Generated by Django 2.1.7 on 2019-04-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190411_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
