# Generated by Django 2.1.7 on 2019-04-24 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_move_users'),
        ('followers', '0002_move_users'),
        ('users', '0004_auto_20190411_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
